### ISSUE TITLE
sparkline

### ISSUE THREAD

**Issue by lauraselby** [DFEAGILEDEVOPS/exclusion-statistics#35]
can we get the sparklines to treat x as 0?

**Comment by TomFranklin** [comment]
Yes, I can create a string function that will change x's to 0's and then that should fix the sparkline issue, will do that on Wednesday!

**Comment by lauraselby** [comment]
I just fixed it... :)

**Comment by TomFranklin** [comment]
Fixing all my issues, I'll be out of a job soon!!

**Comment by TomFranklin** [comment]
By the way, to customise the sparklines, on the edit/reason branch, on the server.R file, line 35 which defines line_string. 

Go to this website https://omnipotent.net/jquery.sparkline/#s-about, display more options, then make it however you fancy, then click code, then use that code to add to the current code inside the " ". Can make some really really cool sparklines!!

**Comment by lauraselby** [comment]
forced x to = 0 for the sake of sparklines, fixing this problem.

**Comment by TomFranklin** [comment]
Is that for all data in the datatable? I could just force it for the column that is used to in the sparklines themselves I'm sure. I'll review on Wednesday.

**Comment by lauraselby** [comment]
just the column for the sparkline
